version: '2'
services:
    apptwo-app:
        image: apptwo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://apptwo-mysql:3306/apptwo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    apptwo-mysql:
        extends:
            file: mysql.yml
            service: apptwo-mysql
